services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    user: root
    environment:
      - PUID=1000
      - PGID=1000
      - SUDO_PASSWORD=test
      - DOCKER_MODS=linuxserver/mods:code-server-python3
    volumes:
      - ./code-server:/config
      - ./conf/start-code-server.sh:/start-code-server.sh
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      - dev
  namenode:
    image: apache/hadoop:3.3.6
    container_name: namenode
    hostname: namenode
    user: root
    env_file:
      - ./.env
    volumes:
      - ./hadoop_namenode:/opt/hadoop/data/nameNode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./conf/start-hdfs.sh:/start-hdfs.sh
    ports:
      - "9870:9870"
      - "8020:8020"
    restart: unless-stopped
    networks:
      - dev
    command: ["/bin/bash", "/start-hdfs.sh"]
  datanode1:
    image: apache/hadoop:3.3.6
    container_name: datanode1
    hostname: datanode1
    user: root
    env_file:
      - ./.env
    volumes:
      - ./hadoop_datanode1:/opt/hadoop/data/dataNode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./conf/init-datanode.sh:/init-datanode.sh
    depends_on:
      - namenode
    restart: unless-stopped
    networks:
      - dev
    command: ["/bin/bash", "/init-datanode.sh"]
  datanode2:
    image: apache/hadoop:3.3.6
    container_name: datanode2
    hostname: datanode2
    user: root
    env_file:
      - ./.env
    volumes:
      - ./hadoop_datanode2:/opt/hadoop/data/dataNode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./conf/init-datanode.sh:/init-datanode.sh
    depends_on:
      - namenode
    restart: unless-stopped
    networks:
      - dev
    command: ["/bin/bash", "/init-datanode.sh"]
  resourcemanager:
    image: apache/hadoop:3.3.6
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    env_file:
      - ./.env
    networks:
      - dev
  nodemanager:
    image: apache/hadoop:3.3.6
    command: ["yarn", "nodemanager"]
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - dev

networks:
  dev:
    driver: bridge
